name: Build Rave Ghost for iPhone 11
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Theos
        uses: logan-arkin/setup-theos@v1.1.0

      - name: Build Tweak
        run: |
          sed -i 's/arm64e/arm64/g' Makefile
          export THEOS_PACKAGE_SCHEME=rootless
          make clean all PACKAGE_FORMAT=dylib
        
      - name: Upload Result
        uses: actions/upload-artifact@v3
        with:
          name: RaveGhost_iPhone11_Ready
          path: .theos/obj/debug/*.dylib
