name: Build Telegram Ultra Ghost
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Theos environment
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
          echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Build Dylib for iPad M4 & iPhone
        run: |
          export THEOS=~/theos
          make all FINALPACKAGE=1
        
      - name: Upload Finished Tweak
        uses: actions/upload-artifact@v4
        with:
          name: Telegram_Ghost_Final
          path: "**/*.dylib"
