name: Build Telegram Ultra Ghost
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Theos
        uses: logan-arkin/setup-theos@v1.1.0

      - name: Build Tweak for M2/M4/iPhone11
        run: |
          make clean all
        
      - name: Upload Dylib Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Telegram_Ghost_M2_M4_Ready
          path: .theos/obj/debug/*.dylib
